# theme: jekyll-theme-cayman
# Aux links for the upper right navigation
aux_links:
  "Fork me on GitHub":
    - "//github.com/LippertComponents/Orchestrator"

remote_theme: pmarsceill/just-the-docs
layout: default
title: Orchestrator
nav_order: 2
has_children: true
permalink: /blend
